// lib/packs/pack_objetos.dart
import '../models.dart';

final List<CartaJuego> packObjetos = [
  CartaJuego("Cepillo de dientes", "Rutina matutina"),
  CartaJuego("Llaves", "Pase"),
  CartaJuego("Paraguas", "Impermeable"),
  CartaJuego("Tijeras", "Doble filo"),
  CartaJuego("Peine", "Rastrillo"),
  CartaJuego("Tenedor", "Tridente"),
  CartaJuego("Cuchara", "Medida"),
  CartaJuego("Cuchillo", "Mango"),
  CartaJuego("Vaso", "Cristal"),
  CartaJuego("Taza", "Cafe"),
  CartaJuego("Plato", "Base"),
  CartaJuego("Sartén", "Aceite"),
  CartaJuego("Olla", "Cámara de vapor"),
  CartaJuego("Toalla", "Fricción"),
  CartaJuego("Jabón", "Olor"),
  CartaJuego("Papel higiénico", "Desechable"),
  CartaJuego("Almohada", "Soporte"),
  CartaJuego("Sábana", "Cubierta"),
  CartaJuego("Manta / Cobija", "Tejido grueso"),
  CartaJuego("Reloj", "Tiempo"),
  CartaJuego("Billetera", "Dinero"),
  CartaJuego("Gafas / Lentes", "Marco"),
  CartaJuego("Mochila", "Carga"),
  CartaJuego("Zapatos", "Piso"),
  CartaJuego("Calcetines", "Pies"),
  CartaJuego("Camisa", "Botones"),
  CartaJuego("Pantalón", "Cierre"),
  CartaJuego("Cinturón", "Lazo de cuero"),
  CartaJuego("Anillo", "Aro metálico"),
  CartaJuego("Pendientes", "Pieza colgante"),
  CartaJuego("Secador de pelo", "Viento"),
  CartaJuego("Plancha", "Caliente"),
  CartaJuego("Escoba", "Cerdas"),
  CartaJuego("Basurero", "Olor"),
  CartaJuego("Bombilla / Foco", "Brillante"),
  CartaJuego("Control remoto", "Distancia"),
  CartaJuego("Televisor", "Caja"),
  CartaJuego("Teléfono móvil", "Pantalla"),
  CartaJuego("Cargador", "Energía"),
  CartaJuego("Mouse", "Deslizante"),
  CartaJuego("Teclado", "Piano"),
  CartaJuego("Cuaderno", "Arboles"),
  CartaJuego("Bolígrafo", "Punta"),
  CartaJuego("Goma de borrar", "Luffy"),
  CartaJuego("Botella", "Cuello estrecho"),
  CartaJuego("Cortaúñas", "Manos"),
  CartaJuego("Desodorante", "Aromática"),
];