// lib/packs/pack_marcas.dart
import '../models.dart';

final List<CartaJuego> packMarcas = [
  CartaJuego("Apple", "14,15,16,17..."),
  CartaJuego("Nike", "Solo hazlo"),
  CartaJuego("Coca-Cola", "Navidad"),
  CartaJuego("McDonald's", "Payaso"),
  CartaJuego("Google", "Explorador"),
  CartaJuego("Amazon", "Jungla"),
  CartaJuego("Disney", "Ratón"),
  CartaJuego("Netflix", "N"),
  CartaJuego("Ferrari", "Caballo"),
  CartaJuego("Rolex", "lujo"),
  CartaJuego("Lego", "Bloques"),
  CartaJuego("IKEA", "Muebles"),
  CartaJuego("Starbucks", "Sirena"),
  CartaJuego("Sony", "la segunda es la mejor"),
  CartaJuego("Pepsi", "_____-Man"),
  CartaJuego("Adidas", "Tres rayas"),
  CartaJuego("Burger King", "El rey"),
  CartaJuego("KFC", "Coronel"),
  CartaJuego("Microsoft", "Ventanas"),
  CartaJuego("Nintendo", "Hermanos"),
  CartaJuego("Gucci", "Ropa de diseñador cara"),
  CartaJuego("Visa", "Tarjeta"),
  CartaJuego("Mastercard", "Tarjeta"),
  CartaJuego("Red Bull", "Alas"),
  CartaJuego("Gillette", "Filo"),
  CartaJuego("Samsung", "Galaxy"),
  CartaJuego("Toyota", "Camionetas muy duraderas"),
  CartaJuego("Bimbo", "Osito"),
  CartaJuego("Colgate", "Blanco"),
  CartaJuego("Nescafé", "Taza"),
  CartaJuego("Puma", "Felino"),
  CartaJuego("Vans", "Skaters"),
  CartaJuego("Converse", "Estrella"),
  CartaJuego("Bic", "Barato"),
  CartaJuego("Michelin", "Comida"),
];