// lib/packs/pack_anime.dart
import '../models.dart';

final List<CartaJuego> packAnime = [
  CartaJuego("Dragon Ball", "Esferas"),
  CartaJuego("Naruto", "Rubio"),
  CartaJuego("One Piece", "Mar"),
  CartaJuego("Attack on Titan", "Cabeza"),
  CartaJuego("Death Note", "Cuaderno"),
  CartaJuego("Demon Slayer", "Cazadores"),
  CartaJuego("Jujutsu Kaisen", "Maldiciones"),
  CartaJuego("My Hero Academia", "Poderes"),
  CartaJuego("Fullmetal Alchemist", "="),
  CartaJuego("Evangelion", "Angeles"),
  CartaJuego("Sword Art Online", "VR"),
  CartaJuego("Tokyo Ghoul", "Comer"),
  CartaJuego("Hunter x Hunter", "Examen"),
  CartaJuego("Bleach", "Almas"),
  CartaJuego("Sailor Moon", "Luna"),
  CartaJuego("Pokémon", "Rayo"),
  CartaJuego("Digimon", "Digital"),
  CartaJuego("JoJo's Bizarre Adventure", "Poses"),
  CartaJuego("One Punch Man", "Golpe"),
  CartaJuego("Chainsaw Man", "Motosierra"),
  CartaJuego("Spy x Family", "Familia"),
  CartaJuego("Cowboy Bebop", "Cazarrecompensas espaciales"),
  CartaJuego("Inuyasha", "Demonios"),
  CartaJuego("Fairy Tail", "Magos"),
  CartaJuego("Black Clover", "Magia"),
  CartaJuego("Nanatsu no Taizai", "Pecados"),
  CartaJuego("Mob Psycho 100", "Psíquicos"),
  CartaJuego("Akira", "Motocicleta"),
  CartaJuego("El Viaje de Chihiro", "Baños termales"),
  CartaJuego("Mi Vecino Totoro", "Espíritu del bosque"),
  CartaJuego("Yu-Gi-Oh!", "Cartas"),
  CartaJuego("Caballeros del Zodiaco", "Armaduras"),
  CartaJuego("Doraemon", "Gato"),
  CartaJuego("Vinland Saga", "Vikingos"),
  CartaJuego("Dr. Stone", "Piedra"),
];