// lib/packs/pack_cine_tv.dart
import '../models.dart';

final List<CartaJuego> packCineTv = [
  // Películas
  CartaJuego("Star Wars", "Fuerza"),
  CartaJuego("Harry Potter", "Cicatriz"),
  CartaJuego("El Señor de los Anillos", "Viaje"),
  CartaJuego("Avengers", "Chasquido"),
  CartaJuego("Batman", "Murciélago"),
  CartaJuego("Spider-Man", "Telaraña"),
  CartaJuego("Titanic", "Iceberg"),
  CartaJuego("Avatar", "Azul"),
  CartaJuego("Jurassic Park", "Huesos"),
  CartaJuego("El Rey León", "Africa"),
  CartaJuego("Toy Story", "Oso"),
  CartaJuego("Shrek", "Lejano"),
  CartaJuego("Frozen", "Frio"),
  CartaJuego("Buscando a Nemo", "Dentista"),
  CartaJuego("Piratas del Caribe", "Barco"),
  CartaJuego("Misión Imposible", "Espía"),
  CartaJuego("Volver al Futuro", "Rayo"),
  CartaJuego("Terminator", "Robot"),
  CartaJuego("Matrix", "Pastilla"),
  CartaJuego("El Padrino", "Caballo"),
  CartaJuego("Rocky", "Boxeo"),
  CartaJuego("Forrest Gump", "Correr"),
  CartaJuego("Gladiador", "Arena"),
  CartaJuego("Coco", "Guitarra"),
  CartaJuego("Intensamente", "Cabeza"),
  CartaJuego("Up", "Globos"),
  CartaJuego("Los Increíbles", "Traje"),
  CartaJuego("Mi Villano Favorito", "Amarillo"),
  CartaJuego("IT", "Barco de Papel"),
  CartaJuego("El Exorcista", "Demonio"),

  // Series de Televisión
  CartaJuego("Breaking Bad", "Profesor"),
  CartaJuego("Game of Thrones", "Dragones"),
  CartaJuego("Stranger Things", "Monstruo"),
  CartaJuego("Los Simpson", "Donas"),
  CartaJuego("Friends", "Cafetería"),
  CartaJuego("The Office", "Papel"),
  CartaJuego("La Casa de Papel", "Atraco"),
  CartaJuego("El Juego del Calamar", "Triangulo"),
  CartaJuego("The Walking Dead", "Muerte"),
  CartaJuego("Peaky Blinders", "Boinas"),
  CartaJuego("Black Mirror", "Tecnología"),
  CartaJuego("Vikings", "Hachas"),
  CartaJuego("Dark", "Viajes en el tiempo"),
  CartaJuego("The Boys", "Superhéroes"),
  CartaJuego("Rick y Morty", "Portal"),
  CartaJuego("South Park", "Nieve"),
  CartaJuego("Bob Esponja", "Cangrejo"),
  CartaJuego("Dragon Ball", "Esferas"),
  CartaJuego("Naruto", "Ninja"),
  CartaJuego("One Piece", "Pirata"),
];