// lib/packs/pack_animales.dart
import '../models.dart'; // Importamos el modelo de CartaJuego

final List<CartaJuego> packAnimales = [
  CartaJuego("León", "Rey"),
  CartaJuego("Tiburón", "Aleta"),
  CartaJuego("Águila", "Visión"),
  CartaJuego("Perro", "Lealtad"),
  CartaJuego("Gato", "Independiente"),
  CartaJuego("Elefante", "Memoria"),
  CartaJuego("Jirafa", "Altura"),
  CartaJuego("Pingüino", "Esmoquin"),
  CartaJuego("Canguro", "Bolsa"),
  CartaJuego("Panda", "Japon"),
  CartaJuego("Lobo", "Luna"),
  CartaJuego("Murciélago", "Eco"),
  CartaJuego("Serpiente", "Veneno"),
  CartaJuego("Cocodrilo", "Lágrimas"),
  CartaJuego("Camaleón", "Color"),
  CartaJuego("Caballo", "Galope"),
  CartaJuego("Vaca", "Leche"),
  CartaJuego("Cerdo", "Lodo"),
  CartaJuego("Oveja", "Lana"),
  CartaJuego("Gallina", "Huevo"),
  CartaJuego("Abeja", "Colmena"),
  CartaJuego("Hormiga", "Fuerza"),
  CartaJuego("Mariposa", "Transformación"),
  CartaJuego("Pulpo", "Tinta"),
  CartaJuego("Delfín", "Inteligente"),
  CartaJuego("Ballena", "Plancton"),
  CartaJuego("Oso Polar", "Hielo"),
  CartaJuego("Zorro", "Astucia"),
  CartaJuego("Búho", "Sabiduría"),
  CartaJuego("Ratón", "Queso"),
  CartaJuego("Conejo", "Zanahoria"),
  CartaJuego("Tortuga", "Lenta"),
  CartaJuego("Caracol", "Casa"),
  CartaJuego("Araña", "Red"),
  CartaJuego("Escorpión", "Aguijón"),
  CartaJuego("Cebra", "Rayas"),
  CartaJuego("Hipopótamo", "Río"),
  CartaJuego("Rinoceronte", "Cuerno"),
  CartaJuego("Gorila", "Selva"),
  CartaJuego("Koala", "Eucalipto"),
  CartaJuego("Perezoso", "Lento"),
  CartaJuego("Flamenco", "Rosa"),
  CartaJuego("Pavo Real", "Abanico"),
  CartaJuego("Loro", "Hablar"),
  CartaJuego("Cisne", "Feo"),
  CartaJuego("Castor", "Presa"),
  CartaJuego("Topo", "Tierra"),
  CartaJuego("Erizo", "Púas"),
];