// lib/packs/pack_animales.dart
import '../models.dart'; // Importamos el modelo de CartaJuego

final List<CartaJuego> packlol = [
  CartaJuego("Aatrox", "Fin del mundo"),
  CartaJuego("Ahri", "Esferas"),
  CartaJuego("Akali", "Humo"),
  CartaJuego("Akshan", "Resurrección"),
  CartaJuego("Alistar", "Campana"),
  CartaJuego("Amumu", "Amigos"),
  CartaJuego("Anivia", "Huevo"),
  CartaJuego("Annie", "Tibbers"),
  CartaJuego("Aphelios", "5 armas"),
  CartaJuego("Ashe", "Flecha"),
  CartaJuego("Aurelion Sol", "Estrellas"),
  CartaJuego("Aurora", "Espíritus"),
  CartaJuego("Azir", "Soldados"),
  CartaJuego("Bard", "Campanas"),
  CartaJuego("Bel'Veth", "Mantarraya"),
  CartaJuego("Blitzcrank", "Gancho"),
  CartaJuego("Brand", "Quemar"),
  CartaJuego("Braum", "Bigote"),
  CartaJuego("Briar", "Hambre"),
  CartaJuego("Caitlyn", "Francotiradora"),
  CartaJuego("Camille", "Tijeras"),
  CartaJuego("Cassiopeia", "Piedra"),
  CartaJuego("Cho'Gath", "Crecer"),
  CartaJuego("Corki", "Paquete"),
  CartaJuego("Darius", "Guillotina"),
  CartaJuego("Diana", "Luna"),
  CartaJuego("Dr. Mundo", "Donde quiere"),
  CartaJuego("Draven", "Hachas"),
  CartaJuego("Ekko", "Rebobinar"),
  CartaJuego("Elise", "Araña"),
  CartaJuego("Evelynn", "Invisible"),
  CartaJuego("Ezreal", "Museo"),
  CartaJuego("Fiddlesticks", "Espantapájaros"),
  CartaJuego("Fiora", "Duelo"),
  CartaJuego("Fizz", "Saltarín"),
  CartaJuego("Galio", "Estatua"),
  CartaJuego("Gangplank", "Naranjas"),
  CartaJuego("Garen", "Arbusto"),
  CartaJuego("Gnar", "Enojo"),
  CartaJuego("Gragas", "Barril"),
  CartaJuego("Graves", "Cigarro"),
  CartaJuego("Gwen", "Costura"),
  CartaJuego("Hecarim", "Caballo"),
  CartaJuego("Heimerdinger", "Torretas"),
  CartaJuego("Hwei", "Pintor"),
  CartaJuego("Illaoi", "Tentáculos"),
  CartaJuego("Irelia", "Danza"),
  CartaJuego("Ivern", "Margarita"),
  CartaJuego("Janna", "Tornado"),
  CartaJuego("Jarvan IV", "Cráter"),
  CartaJuego("Jax", "Lámpara"),
  CartaJuego("Jayce", "Martillo"),
  CartaJuego("Jhin", "Cuatro"),
  CartaJuego("Jinx", "Cohetes"),
  CartaJuego("K'Sante", "Tanque"),
  CartaJuego("Kai'Sa", "Piel"),
  CartaJuego("Kalista", "Venganza"),
  CartaJuego("Karma", "Mantra"),
  CartaJuego("Karthus", "Réquiem"),
  CartaJuego("Kassadin", "Vacío"),
  CartaJuego("Katarina", "Dagas"),
  CartaJuego("Kayle", "Justicia"),
  CartaJuego("Kayn", "Guadaña"),
  CartaJuego("Kennen", "Electricidad"),
  CartaJuego("Kha'Zix", "Evolución"),
  CartaJuego("Kindred", "Lobo"),
  CartaJuego("Kled", "Lagartija"),
  CartaJuego("Kog'Maw", "Saliva"),
  CartaJuego("LeBlanc", "Engaño"),
  CartaJuego("Lee Sin", "Ciego"),
  CartaJuego("Leona", "Sol"),
  CartaJuego("Lillia", "Dormir"),
  CartaJuego("Lissandra", "Hielo"),
  CartaJuego("Lucian", "Pistolas"),
  CartaJuego("Lulu", "Hada"),
  CartaJuego("Lux", "Arcoíris"),
  CartaJuego("Malphite", "Roca"),
  CartaJuego("Malzahar", "Supresión"),
  CartaJuego("Maokai", "Árbol"),
  CartaJuego("Master Yi", "Alpha"),
  CartaJuego("Milio", "Fuego"),
  CartaJuego("Miss Fortune", "Pirata"),
  CartaJuego("Mordekaiser", "Reino"),
  CartaJuego("Morgana", "Cárcel"),
  CartaJuego("Naafiri", "Manada"),
  CartaJuego("Nami", "Ola"),
  CartaJuego("Nasus", "Farmear"),
  CartaJuego("Nautilus", "Ancla"),
  CartaJuego("Neeko", "Camuflaje"),
  CartaJuego("Nidalee", "Lanza"),
  CartaJuego("Nilah", "Alegría"),
  CartaJuego("Nocturne", "Oscuridad"),
  CartaJuego("Nunu & Willump", "Bola"),
  CartaJuego("Olaf", "Vikingo"),
  CartaJuego("Orianna", "Bola"),
  CartaJuego("Ornn", "Forja"),
  CartaJuego("Pantheon", "Espartano"),
  CartaJuego("Poppy", "Héroe"),
  CartaJuego("Pyke", "Lista"),
  CartaJuego("Qiyana", "Elementos"),
  CartaJuego("Quinn", "Valor"),
  CartaJuego("Rakan", "Encanto"),
  CartaJuego("Rammus", "Ok"),
  CartaJuego("Rek'Sai", "Túneles"),
  CartaJuego("Rell", "Metal"),
  CartaJuego("Renata Glasc", "Química"),
  CartaJuego("Renekton", "Cocodrilo"),
  CartaJuego("Rengar", "Trofeos"),
  CartaJuego("Riven", "Rota"),
  CartaJuego("Rumble", "Calor"),
  CartaJuego("Ryze", "Pergamino"),
  CartaJuego("Samira", "Estilo"),
  CartaJuego("Sejuani", "Jabalí"),
  CartaJuego("Senna", "Niebla"),
  CartaJuego("Seraphine", "Cantante"),
  CartaJuego("Sett", "Abdominales"),
  CartaJuego("Shaco", "Clon"),
  CartaJuego("Shen", "Equilibrio"),
  CartaJuego("Shyvana", "Dragón"),
  CartaJuego("Singed", "Veneno"),
  CartaJuego("Sion", "Tren"),
  CartaJuego("Sivir", "Boomerang"),
  CartaJuego("Skarner", "Escorpión"),
  CartaJuego("Smolder", "Mamá"),
  CartaJuego("Sona", "Muda"),
  CartaJuego("Soraka", "Banana"),
  CartaJuego("Swain", "Cuervos"),
  CartaJuego("Sylas", "Robar"),
  CartaJuego("Syndra", "Poder"),
  CartaJuego("Tahm Kench", "Rana"),
  CartaJuego("Taliyah", "Muro"),
  CartaJuego("Talon", "Parkour"),
  CartaJuego("Taric", "Gemas"),
  CartaJuego("Teemo", "Setas"),
  CartaJuego("Thresh", "Linterna"),
  CartaJuego("Tristana", "Cañón"),
  CartaJuego("Trundle", "Troll"),
  CartaJuego("Tryndamere", "Inmortal"),
  CartaJuego("Twisted Fate", "Cartas"),
  CartaJuego("Twitch", "Rata"),
  CartaJuego("Udyr", "Posiciones"),
  CartaJuego("Urgot", "Piernas"),
  CartaJuego("Varus", "Flecha"),
  CartaJuego("Vayne", "Gafas"),
  CartaJuego("Veigar", "Pequeño"),
  CartaJuego("Vel'Koz", "Geometría"),
  CartaJuego("Vex", "Sombra"),
  CartaJuego("Vi", "Guanteletes"),
  CartaJuego("Viego", "Rey"),
  CartaJuego("Viktor", "Láser"),
  CartaJuego("Vladimir", "Sangre"),
  CartaJuego("Volibear", "Oso"),
  CartaJuego("Warwick", "Olfato"),
  CartaJuego("Wukong", "Mono"),
  CartaJuego("Xayah", "Plumas"),
  CartaJuego("Xerath", "Arcano"),
  CartaJuego("Xin Zhao", "Lanza"),
  CartaJuego("Yasuo", "Viento"),
  CartaJuego("Yone", "Espíritu"),
  CartaJuego("Yorick", "Pala"),
  CartaJuego("Yuumi", "Gato"),
  CartaJuego("Zac", "Gelatina"),
  CartaJuego("Zed", "Sombras"),
  CartaJuego("Zeri", "Chispa"),
  CartaJuego("Ziggs", "Bombas"),
  CartaJuego("Zilean", "Reloj"),
  CartaJuego("Zoe", "Dormir"),
  CartaJuego("Zyra", "Plantas"),
];