// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdWgH5y2nA22OsH4t53VlR6XPzpB8Q_0I',
    appId: '1:370050164069:web:36bc55240804a8feb5ed8c',
    messagingSenderId: '370050164069',
    projectId: 'impostor-53fc4',
    authDomain: 'impostor-53fc4.firebaseapp.com',
    databaseURL: 'https://impostor-53fc4-default-rtdb.firebaseio.com',
    storageBucket: 'impostor-53fc4.firebasestorage.app',
    measurementId: 'G-44F2X2QD2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-LFot2-fXG6KwI84expxe8wWM7uVkik',
    appId: '1:370050164069:android:cd8bc75cd6d7cec0b5ed8c',
    messagingSenderId: '370050164069',
    projectId: 'impostor-53fc4',
    databaseURL: 'https://impostor-53fc4-default-rtdb.firebaseio.com',
    storageBucket: 'impostor-53fc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqjHYRFXohMG0jJy4_1SJlg9lawp0Tpd0',
    appId: '1:370050164069:ios:06a9fc8bd34063a3b5ed8c',
    messagingSenderId: '370050164069',
    projectId: 'impostor-53fc4',
    databaseURL: 'https://impostor-53fc4-default-rtdb.firebaseio.com',
    storageBucket: 'impostor-53fc4.firebasestorage.app',
    iosBundleId: 'com.example.impostor2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqjHYRFXohMG0jJy4_1SJlg9lawp0Tpd0',
    appId: '1:370050164069:ios:06a9fc8bd34063a3b5ed8c',
    messagingSenderId: '370050164069',
    projectId: 'impostor-53fc4',
    databaseURL: 'https://impostor-53fc4-default-rtdb.firebaseio.com',
    storageBucket: 'impostor-53fc4.firebasestorage.app',
    iosBundleId: 'com.example.impostor2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdWgH5y2nA22OsH4t53VlR6XPzpB8Q_0I',
    appId: '1:370050164069:web:2be9b4491d2f355cb5ed8c',
    messagingSenderId: '370050164069',
    projectId: 'impostor-53fc4',
    authDomain: 'impostor-53fc4.firebaseapp.com',
    databaseURL: 'https://impostor-53fc4-default-rtdb.firebaseio.com',
    storageBucket: 'impostor-53fc4.firebasestorage.app',
    measurementId: 'G-HV0V4XN3TG',
  );
}
